/**
 * Utility to generate and download quality assessment reports
 */

export const generateQualityReport = (fileData) => {
    const report = {
        file_name: fileData.file_name,
        processed_at: fileData.processed_at,
        overall_quality_score: fileData.overall_quality_score || fileData.quality_score,
        recommended_action: fileData.recommended_action,
        dimensions: fileData.dimensions || {},
        dimension_approvals: fileData.dimension_approvals || {},
        summary: fileData.summary,
        context: fileData.context,
        metadata: fileData.metadata
    };

    return report;
};

export const downloadAsJSON = (fileData, fileName = null) => {
    const report = generateQualityReport(fileData);
    const jsonStr = JSON.stringify(report, null, 2);
    const blob = new Blob([jsonStr], { type: 'application/json' });
    const url = URL.createObjectURL(blob);

    const link = document.createElement('a');
    link.href = url;
    link.download = fileName || `quality_report_${fileData.file_name}_${new Date().toISOString().split('T')[0]}.json`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
};

export const downloadAsText = (fileData, fileName = null) => {
    const report = generateQualityReport(fileData);

    let textReport = `
╔═══════════════════════════════════════════════════════════════╗
║           DATA QUALITY ASSESSMENT REPORT                      ║
╚═══════════════════════════════════════════════════════════════╝

File Name: ${report.file_name}
Processed: ${new Date(report.processed_at).toLocaleString()}
Overall Quality Score: ${report.overall_quality_score}/100
Recommended Action: ${report.recommended_action}

═══════════════════════════════════════════════════════════════

SUMMARY
${report.summary || 'N/A'}

CONTEXT
${report.context || 'N/A'}

═══════════════════════════════════════════════════════════════

17-DIMENSION QUALITY ASSESSMENT
`;

    // Add each dimension
    const dimensionNames = [
        'Accuracy', 'Completeness', 'Consistency', 'Timeliness', 'Validity',
        'Uniqueness', 'Reliability', 'Relevance', 'Accessibility', 'Precision',
        'Integrity', 'Conformity', 'Interpretability', 'Traceability',
        'Credibility', 'Fitness_for_Use', 'Value'
    ];

    dimensionNames.forEach(dimName => {
        const dim = report.dimensions[dimName];
        const approval = report.dimension_approvals[dimName];

        if (dim) {
            textReport += `\n${dimName.replace(/_/g, ' ')}:\n`;
            textReport += `  Score: ${dim.score}/100\n`;
            textReport += `  Evidence: ${dim.evidence}\n`;

            if (approval) {
                textReport += `  Status: ${approval.status.toUpperCase()}\n`;
                if (approval.feedback) {
                    textReport += `  Feedback: ${approval.feedback}\n`;
                }
                textReport += `  Reviewed: ${new Date(approval.timestamp).toLocaleString()}\n`;
            } else {
                textReport += `  Status: PENDING REVIEW\n`;
            }
            textReport += `\n`;
        }
    });

    textReport += `
═══════════════════════════════════════════════════════════════

METADATA
`;

    if (report.metadata) {
        Object.entries(report.metadata).forEach(([key, value]) => {
            if (Array.isArray(value) && value.length > 0) {
                textReport += `\n${key.toUpperCase()}:\n`;
                value.forEach(item => {
                    textReport += `  - ${item}\n`;
                });
            }
        });
    }

    textReport += `
═══════════════════════════════════════════════════════════════
Report generated by Aether Intelligence Data Quality System
${new Date().toLocaleString()}
═══════════════════════════════════════════════════════════════
`;

    const blob = new Blob([textReport], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);

    const link = document.createElement('a');
    link.href = url;
    link.download = fileName || `quality_report_${fileData.file_name}_${new Date().toISOString().split('T')[0]}.txt`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
};
